spring:
  application:
    name: tasktracker
  datasource:
    url: jdbc:postgresql://localhost:5432/task_tracker
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
token:
  expiration: 86400000
  key: ${TOKEN_SECRET_KEY}
logging:
  level:
    org:
      springframework:
        security: DEBUG